### PR TITLE
Bugfix no tests if no internet

### PR DESCRIPTION
**Pull request by PMassicotte**
- Fixes CRAN checks: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/gitignore-00check.html

### CODE REVIEW

**Comment by maelle** [comment]
I think you'd be safer with `skip_on_cran()` as I vaguely remember having issues in codemetar when using `skip_offline()` only as it'd fail on some platform.

So I'd make it

```r
skip_on_cran()
skip_offline()
```

(the order is important :sweat_smile: )

I'd also subjectively recommend checking out https://books.ropensci.org/http-testing/ especially https://books.ropensci.org/http-testing/graceful.html and https://books.ropensci.org/http-testing/cran-preparedness.html

**Comment by PMassicotte** [comment]
Thank you very much @maelle for pointing that out and the references :)

**Comment by maurolepore** [comment]
I see you updated the gh-actions workflow for R CMD check. Maybe it's a good time to re-run `usethis::use_github_action("check-full")`? The workflow changed quite a bit and I think the new way of referring to older versions of R is pretty clever (e.g. `oldrel-4`).

https://github.com/r-lib/actions/blob/master/examples/check-full.yaml

(Note the new name for that workflow is check-full.yaml.)

**Comment by PMassicotte** [comment]
I am getting this:

```r
> usethis::use_github_actions("check-full")
Error in usethis::use_github_actions("check-full") : 
  unused argument ("check-full")
```

**Comment by maurolepore** [comment]
Above I made a typo and I now fixed it. 

```r
# Good
usethis::use_github_action("check-full")
# Bad
usethis::use_github_actions("check-full")
```

https://usethis.r-lib.org/reference/github_actions.html

**Pull request merged**
