### PR TITLE
Donot use xsel linux

### PR DESCRIPTION
**Pull request by PMassicotte**
@maurolepore @aedobbyn @melvidoni I have made some change to address #7. Can you verify that everything is fine? Maybe we could ask @jennybc for a quick look if she has time. Thank you, everyone.

### CODE REVIEW

**Comment by jennybc** [comment]
I haven't looked at your package but a change in `.travis.yml` can't have any effect on what's happening on CRAN. So if your package is launching an xsel process on their machines, I don't think this PR could possibly fix that.

The offender is mostly like a test, example, or vignette chunk that executes and causes the clipboard to get touched.

**Comment by PMassicotte** [comment]
Thank you very much for your insights. Much appreciated.

**Comment by melvidoni** [comment]
You are cleared to merge @PMassicotte! Let me know if you can't do it.

**Comment by PMassicotte** [comment]
I have followed the advice from Jenny, I think we could resubmit to CRAN. What do you all think?

**Comment by aedobbyn** [comment]
Does it still build okay on winbuilder and r-hub?

**Comment by PMassicotte** [comment]
Yes, it builds no errors. We had that before, but apparently, it was not ok to use the clipboard on CRAN.

**Comment by aedobbyn** [comment]
Cool seems good to go to me then!

**Pull request merged**
